### PR TITLE
Inverse trig functions

### PR DESCRIPTION
**Pull request by anj1**
This PR adds a feature that I've long wanted to add to this repo: inverse trig functions and inverse log.

`log_alg` works by checking if the polynomial coefficients for the algebraic number are cyclotomic. A fast algorithm (using the inverse of the Euler totient function) is used to check If this polynomial is the nth cyclotomic polynomial for some n. If so, then the denominator of the result is simply n. Once the denominator is known, calculation of the numerator is straightforward.

Also added tests for these functions and updated the readme.

### CODE REVIEW

**Comment by fkastner** [comment]
I didn't check the math but in my limited tests it seems to work :)

The CI fails on v1.0  because `isnothing` was only introduced in Julia v1.1.
The failure on v1.6 says that this check failed for `x=1//10`:
```julia
Expression: cos_alg(x - 1 // 2) == sin_alg(x)
   Evaluated: ≈0.30901699437494745 + 0.0im == ≈0.30901699437494745 - 0.0im
```
I don't know why that failed, it seems those two should be equal. The coefficients of those two numbers are `BigInt[-1, 2, 4]` and `BigInt[1, -6, 16, -16, 16]`. Shouldn't they be equal?

I noticed that none of the trig functions are typestable (`@code_warntype` seems to only infer `Any`) but maybe this can be fixed in a follow-up PR.
Also what do you think about extending Base functions (`exp`, `sin`, etc.) for `AlgebraicNumber`s instead of defining separate functions `exp_alg`, `sin_alg`, etc.? We would require `AlgebraicNumber`s as input to output `AlgebraicNumber`s. For convenience a macro `@algebraic` could be provided to convert all occuring numbers into `AlgebraicNumber`s (cf. [@nice](https://github.com/fkastner/NiceNumbers.jl/blob/b6175fb686ff8b0571acbc092f540596f832b6c7/src/NiceNumbers.jl#LL178-L188)).

**Comment by anj1** [comment]
All good ideas. For renaming them to, for example, `exp` instead of `exp_alg`, the main barrier is that the numerical values actually aren't compatible. E.g. `exp_alg(1//2) = 1i` but  `exp(1//2) = 1.648721`. Thus the functions are actually conceptually different. However this could be fixed if we defined a new number type, like `RationalMultipleOfPi` and made `exp_alg` only accept values of this type. So then `RationalMultipleOfPi(1//2)` would actually have the value `π/2` and would be displayed/converted/promoted as such. This is probably more consistent and julian than the current way I'm doing it; the downside is the need for an  extra number type, but I think this should be ok?

> I noticed that none of the trig functions are typestable (@code_warntype seems to only infer Any) but maybe this can be fixed in a follow-up PR.

Good point, the return type should probably be `Union{Nothing, Int}`, or maybe it should just throw a `ValueError` for non-root-of-unity input. Not sure what would be more user friendly here.

> For convenience a macro @algebraic could be provided to convert all occuring numbers into AlgebraicNumbers.

Yep I noticed that in your repo and it would be good to have here too.

> The coefficients of those two numbers are BigInt[-1, 2, 4] and BigInt[1, -6, 16, -16, 16]. Shouldn't they be equal?

This was a regression from my changing `exp_alg` to use a faster method based on cyclotomic polynomials. Investigating it, it actually failed for all even numerators (silly me...). I had mistakenly done `2*denominator` rather than dividing the rational number by half. I pushed a change that should fix it hopefully. This also removes the need for the check that the number is 0 (the fact that the check was necessary should have been my clue that something was wrong!)

**Comment by fkastner** [comment]
To address the failure on 1.0: since 1.6 is the new LTS version, I think we should just drop support for 1.0. I.e. raise the compat entry in the `Project.toml` to at least 1.1 (the version where `isnothing` was introduced) and change the CI to test on 1.1 and 1.6 (the new LTS) instead of 1.0. I can do that in a new PR.

**Review by fkastner — APPROVED** [review]
Let's merge this and address the type instabilities in a new PR.

**Pull request merged**
